import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import BahirjiChatbot from '../components/BahirjiChatbot';
import CrowdStatusBadge from '../components/CrowdStatusBadge';
import EmergencyButton from '../components/EmergencyButton';
import { staticForts } from '../data/staticForts';
import { fortDetailedData } from '../data/fortDetailedData';
import {
    FaMapMarkerAlt, FaClock, FaRupeeSign, FaHistory,
    FaStar, FaHiking, FaMountain, FaArrowLeft, FaExternalLinkAlt,
    FaCalendarAlt, FaTicketAlt, FaChevronRight, FaRobot, FaUsers,
    FaWikipediaW, FaMonument, FaUtensils, FaExclamationTriangle,
    FaDownload
} from 'react-icons/fa';
import { GiCastle } from 'react-icons/gi';

const API_BASE = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';

/* ═══════════════════════════════════════════════
   TEXT ITINERARY GENERATOR
   ═══════════════════════════════════════════════ */
const generateTextItinerary = (fort, detail) => {
    const d = new Date().toISOString().split('T')[0];
    const line = '═'.repeat(52);
    let txt = '';

    txt += `╔${'═'.repeat(52)}╗\n`;
    txt += `║     🏰 MAHAFORT GUIDE — FORT ITINERARY             ║\n`;
    txt += `╚${'═'.repeat(52)}╝\n\n`;
    txt += `Fort: ${fort.name}\n`;
    txt += `District: ${fort.location?.district}, Maharashtra\n`;
    txt += `Altitude: ${fort.altitude || 'N/A'}\n`;
    txt += `Difficulty: ${fort.difficulty}\n`;
    txt += `Generated: ${d}\n\n`;

    txt += `${line}\n📜 INTRODUCTION\n${line}\n\n`;
    txt += `${(detail?.introduction || fort.description || '').replace(/\s+/g, ' ').trim()}\n\n`;

    if (detail?.timeline?.length) {
        txt += `${line}\n📅 HISTORICAL TIMELINE\n${line}\n\n`;
        detail.timeline.forEach(t => {
            txt += `  ┌─── ${t.year} ───┐\n`;
            txt += `  │ ${t.title}\n`;
            txt += `  │ ${t.desc}\n`;
            txt += `  └${'─'.repeat(40)}┘\n\n`;
        });
    }

    if (detail?.landmarks?.length) {
        txt += `${line}\n🏛️ KEY LANDMARKS\n${line}\n\n`;
        detail.landmarks.forEach((l, i) => {
            txt += `  ${i + 1}. ${l.title}${l.mustSee ? ' ⭐ MUST SEE' : ''}\n`;
            txt += `     ${l.desc}\n\n`;
        });
    }

    if (detail?.trekRoutes?.length) {
        txt += `${line}\n🥾 TREK ROUTES\n${line}\n\n`;
        detail.trekRoutes.forEach(r => {
            txt += `  ${r.icon} ${r.title}\n`;
            txt += `     Difficulty: ${r.difficulty} | Distance: ${r.distance} | Time: ${r.time}\n`;
            txt += `     ${r.desc}\n\n`;
        });
    }

    if (detail?.howToReach?.length) {
        txt += `${line}\n🚌 HOW TO REACH\n${line}\n\n`;
        detail.howToReach.forEach(h => {
            txt += `  ${h.icon} ${h.mode}\n     ${h.desc}\n\n`;
        });
    }

    if (detail?.food?.length) {
        txt += `${line}\n🍽️ FOOD & CUISINE\n${line}\n\n`;
        detail.food.forEach(f => {
            txt += `  • ${f.name} (${f.type}) — ${f.price}\n`;
            txt += `    ${f.desc}\n\n`;
        });
    }

    if (detail?.budget?.length) {
        txt += `${line}\n💰 BUDGET ESTIMATE (Per Person)\n${line}\n\n`;
        detail.budget.forEach(b => {
            txt += `  ${b.highlight ? '▶' : ' '} ${b.label.padEnd(15)} ${b.value}\n`;
        });
        txt += '\n';
    }

    if (detail?.trekEssentials?.length) {
        txt += `${line}\n🎒 PACKING CHECKLIST\n${line}\n\n`;
        detail.trekEssentials.forEach(t => {
            txt += `  ☐ ${t}\n`;
        });
        txt += '\n';
    }

    if (detail?.safetyAlerts?.length) {
        txt += `${line}\n⚠️ SAFETY ALERTS\n${line}\n\n`;
        detail.safetyAlerts.forEach(a => {
            txt += `  ⚠ ${a.msg}\n    Season: ${a.season}\n\n`;
        });
    }

    txt += `${line}\n📞 EMERGENCY CONTACTS\n${line}\n\n`;
    txt += `  Police:     100\n`;
    txt += `  Ambulance:  108\n`;
    txt += `  Emergency:  112\n\n`;
    txt += `${'─'.repeat(52)}\n`;
    txt += `Generated by MahaFort Guide — mahafort.guide\n`;
    txt += `Jai Maharashtra! 🚩\n`;

    return txt;
};

/* ═══════════════════════════════════════════════
   MAIN COMPONENT
   ═══════════════════════════════════════════════ */
const FortDetails = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [fort, setFort] = useState(null);
    const [agentData, setAgentData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [agentLoading, setAgentLoading] = useState(false);
    const [agentLogs, setAgentLogs] = useState([]);
    const [activeTab, setActiveTab] = useState('history');
    const [showMap, setShowMap] = useState(false);

    // Find fort
    useEffect(() => {
        window.scrollTo(0, 0);
        setActiveTab('history');
        const foundFort = staticForts.find(
            f => f._id === id || f.name.toLowerCase().replace(/\s+/g, '-') === id
        );
        if (foundFort) setFort(foundFort);

        fetch(`${API_BASE}/forts/${id}`)
            .then(r => r.ok ? r.json() : null)
            .then(data => { if (data) setFort(prev => prev ? { ...prev, ...data } : data); })
            .catch(() => { })
            .finally(() => setLoading(false));
    }, [id]);

    // Fort Agent SSE
    const runAgent = useCallback(() => {
        if (!fort?.name || agentLoading) return;
        setAgentLoading(true);
        setAgentLogs([]);
        const es = new EventSource(`${API_BASE}/agent/search?query=${encodeURIComponent(fort.name)}`);
        es.onmessage = (event) => {
            try {
                const data = JSON.parse(event.data);
                if (data.type === 'log') setAgentLogs(prev => [...prev, data.message]);
                else if (data.type === 'result') { setAgentData(data.data); setAgentLoading(false); es.close(); }
                else if (data.type === 'error') { setAgentLoading(false); es.close(); }
            } catch (e) { /* ignore */ }
        };
        es.onerror = () => { setAgentLoading(false); es.close(); };
    }, [fort, agentLoading]);

    // Download text itinerary
    const downloadTextItinerary = () => {
        if (!fort) return;
        const detail = fortDetailedData[fort._id];
        const text = generateTextItinerary(fort, detail);
        const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `MahaFort_${fort.name.replace(/\s+/g, '_')}_Itinerary.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-royal-black text-white">
                <Navbar />
                <div className="flex items-center justify-center h-[70vh]">
                    <div className="text-center">
                        <div className="w-16 h-16 border-4 border-saffron border-t-transparent rounded-full animate-spin mx-auto"></div>
                        <p className="mt-4 text-saffron font-cinematic animate-pulse tracking-widest">Loading Fort Data...</p>
                    </div>
                </div>
            </div>
        );
    }

    if (!fort) {
        return (
            <div className="min-h-screen bg-royal-black text-white">
                <Navbar />
                <div className="flex items-center justify-center h-[70vh]">
                    <div className="text-center">
                        <GiCastle className="text-gray-700 text-7xl mx-auto mb-4" />
                        <h2 className="text-3xl font-cinematic font-bold text-gray-400 mb-4">Fort Not Found</h2>
                        <p className="text-gray-600 mb-6">Could not find data for fort: {id}</p>
                        <button onClick={() => navigate('/forts')}
                            className="px-6 py-3 bg-saffron/10 border border-saffron/30 rounded-xl text-saffron font-bold hover:bg-saffron/20 transition-all">
                            ← Back to Forts
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    const detail = fortDetailedData[fort._id];
    const hasDetail = !!detail;
    const defaultImage = 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=80';
    const heroImage = fort.images?.[0] || defaultImage;
    const isDefaultImage = typeof heroImage === 'string' && heroImage.includes('unsplash.com');

    const diffColors = {
        Easy: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
        Moderate: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
        Difficult: 'text-red-400 bg-red-500/10 border-red-500/30',
        Hard: 'text-red-400 bg-red-500/10 border-red-500/30',
    };
    const dc = diffColors[fort.difficulty] || diffColors.Moderate;

    const coordinates = agentData?.coordinates;
    const googleMapsUrl = coordinates
        ? `https://www.google.com/maps/search/?api=1&query=${coordinates.lat},${coordinates.lon}`
        : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(fort.name + ' Maharashtra')}`;

    const desc = agentData?.description || detail?.introduction || fort.description;
    const tabs = hasDetail
        ? [
            { key: 'history', label: 'History', icon: '📜' },
            { key: 'landmarks', label: 'Landmarks', icon: '🏛️' },
            { key: 'food', label: 'Food & Culture', icon: '🍽️' },
            { key: 'trek', label: 'Trek Guide', icon: '🥾' }
        ]
        : [{ key: 'history', label: 'About', icon: '📜' }];

    return (
        <div className="min-h-screen bg-royal-black text-white font-body selection:bg-saffron selection:text-black">
            <Navbar />
            <BahirjiChatbot />

            {/* ═══ CINEMATIC HERO ═══ */}
            <div className="relative h-[55vh] sm:h-[65vh] overflow-hidden">
                <img src={heroImage} alt={fort.name}
                    className={`absolute inset-0 w-full h-full object-cover ${isDefaultImage ? 'opacity-25' : 'opacity-45'} scale-105`}
                    style={{ filter: 'saturate(0.8)' }} />
                <div className="absolute inset-0 bg-gradient-to-t from-royal-black via-royal-black/70 to-royal-black/20" />
                <div className="absolute inset-0 bg-gradient-to-r from-royal-black/50 to-transparent" />

                {/* Saffron accent line */}
                <div className="absolute bottom-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-saffron to-transparent opacity-60"></div>

                {/* Back button */}
                <div className="absolute top-24 left-6 z-10">
                    <button onClick={() => navigate('/forts')}
                        className="flex items-center gap-2 px-4 py-2 bg-black/50 backdrop-blur-md border border-white/10 rounded-xl text-white/80 hover:text-saffron hover:border-saffron/30 transition-all text-sm">
                        <FaArrowLeft size={12} /> All Forts
                    </button>
                </div>

                {/* Hero Content */}
                <div className="absolute bottom-0 left-0 right-0 p-6 sm:p-12">
                    <div className="container mx-auto max-w-6xl">
                        <div className="flex flex-wrap items-center gap-3 mb-4">
                            <span className={`px-3 py-1 rounded-lg text-xs font-bold uppercase tracking-wider border ${dc}`}>
                                {fort.difficulty}
                            </span>
                            <span className="px-3 py-1 rounded-lg bg-saffron/10 border border-saffron/30 text-saffron text-xs font-bold uppercase tracking-wider">
                                {fort.type || 'Hill Fort'}
                            </span>
                            {fort.altitude && (
                                <span className="px-3 py-1 rounded-lg bg-blue-500/10 border border-blue-500/30 text-blue-400 text-xs font-bold">
                                    <FaMountain className="inline mr-1" size={10} /> {fort.altitude}
                                </span>
                            )}
                        </div>

                        <h1 className="text-4xl sm:text-5xl md:text-7xl font-cinematic font-black mb-3 leading-tight">
                            {fort.name.replace(' Fort', '').replace(' Peak', '')}
                            <span className="text-saffron"> {fort.name.includes('Peak') ? 'Peak' : 'Fort'}</span>
                        </h1>

                        <div className="flex flex-wrap items-center gap-4 text-gray-400 text-sm">
                            <span className="flex items-center gap-1.5">
                                <FaMapMarkerAlt className="text-saffron" />
                                {fort.location?.district}, {fort.location?.state || 'Maharashtra'}
                            </span>
                            {fort.rating && (
                                <span className="flex items-center gap-1.5">
                                    <FaStar className="text-amber-500" /> {fort.rating} / 5
                                </span>
                            )}
                            {fort.visitors && (
                                <span className="flex items-center gap-1.5">
                                    <FaUsers className="text-saffron/60" />
                                    ~{(fort.visitors / 1000).toFixed(0)}k visitors/year
                                </span>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            {/* ═══ QUICK STAT BAR ═══ */}
            <div className="bg-royal-gray/80 backdrop-blur-xl border-b border-white/5">
                <div className="container mx-auto max-w-6xl flex flex-wrap justify-center md:justify-between divide-x divide-white/5 py-2">
                    <QuickStat icon="⛰️" label="Altitude" value={fort.altitude || 'N/A'} />
                    <QuickStat icon="⭐" label="Rating" value={`${fort.rating || '—'} / 5`} />
                    <QuickStat icon="🥾" label="Difficulty" value={fort.difficulty} />
                    <QuickStat icon="📍" label="District" value={fort.location?.district} />
                    {fort.entryFee && <QuickStat icon="🎫" label="Entry" value={fort.entryFee} />}
                </div>
            </div>

            {/* ═══ MAIN CONTENT ═══ */}
            <div className="container mx-auto max-w-6xl px-4 sm:px-6 py-8 sm:py-12">
                <div className="flex flex-col lg:flex-row gap-8">

                    {/* LEFT COLUMN */}
                    <div className="lg:w-2/3 space-y-8">

                        {/* Introduction / Quote */}
                        <section>
                            <p className="text-gray-300 text-lg leading-relaxed first-letter:text-5xl first-letter:font-cinematic first-letter:text-saffron first-letter:font-bold first-letter:float-left first-letter:mr-3 first-letter:mt-1">
                                {desc}
                            </p>
                            {detail?.quote && (
                                <div className="mt-6 bg-white/[0.03] border-l-4 border-saffron p-6 rounded-r-xl">
                                    <p className="italic text-xl text-gray-200 font-cinematic">"{detail.quote.text}"</p>
                                    <span className="block text-sm text-saffron/70 mt-2">— {detail.quote.attribution}</span>
                                </div>
                            )}
                            {fort.historicalSignificance && (
                                <div className="mt-4 p-4 bg-saffron/5 border border-saffron/20 rounded-xl">
                                    <p className="text-saffron text-sm font-bold mb-1">⚡ Historical Significance</p>
                                    <p className="text-gray-300 text-sm">{fort.historicalSignificance}</p>
                                </div>
                            )}
                        </section>

                        {/* ═══ TABS ═══ */}
                        {hasDetail && (
                            <div className="flex gap-1 overflow-x-auto pb-2 border-b border-white/10">
                                {tabs.map(tab => (
                                    <button key={tab.key}
                                        onClick={() => setActiveTab(tab.key)}
                                        className={`flex items-center gap-2 px-5 py-3 rounded-t-xl font-cinematic font-bold text-sm whitespace-nowrap transition-all duration-300
                                            ${activeTab === tab.key
                                                ? 'bg-white/10 text-saffron border-b-2 border-saffron'
                                                : 'text-gray-500 hover:text-white hover:bg-white/5'}`}>
                                        <span>{tab.icon}</span> {tab.label}
                                    </button>
                                ))}
                            </div>
                        )}

                        {/* HISTORY TAB */}
                        {activeTab === 'history' && (
                            <section className="animate-fade-in space-y-6">
                                <h2 className="flex items-center gap-3 text-3xl font-cinematic font-bold text-white pb-2 border-b border-white/10">
                                    <FaHistory className="text-saffron" />
                                    {hasDetail ? 'Historical Timeline' : 'History'}
                                </h2>

                                {/* Basic history for forts without detail */}
                                {!hasDetail && (fort.history?.builtBy || fort.history?.year) && (
                                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                        {fort.history.builtBy && (
                                            <div className="p-4 bg-amber-500/5 border border-amber-500/20 rounded-xl">
                                                <p className="text-amber-400 text-xs font-bold uppercase tracking-wider mb-1">Built By</p>
                                                <p className="text-white font-bold">{fort.history.builtBy}</p>
                                            </div>
                                        )}
                                        {fort.history.year && (
                                            <div className="p-4 bg-blue-500/5 border border-blue-500/20 rounded-xl">
                                                <p className="text-blue-400 text-xs font-bold uppercase tracking-wider mb-1">Year / Period</p>
                                                <p className="text-white font-bold">{fort.history.year}</p>
                                            </div>
                                        )}
                                    </div>
                                )}

                                {/* Rich timeline for detailed forts */}
                                {detail?.timeline && (
                                    <div className="space-y-1">
                                        {detail.timeline.map((t, i) => (
                                            <TimelineItem key={i} year={t.year} title={t.title} desc={t.desc} />
                                        ))}
                                    </div>
                                )}

                                {agentData?.history && (
                                    <div className="bg-white/[0.03] border border-white/10 rounded-xl p-6">
                                        <h3 className="text-saffron font-cinematic font-bold mb-2">🤖 Agent-Retrieved History</h3>
                                        <p className="text-gray-400 leading-relaxed text-sm">{agentData.history}</p>
                                    </div>
                                )}
                            </section>
                        )}

                        {/* LANDMARKS TAB */}
                        {activeTab === 'landmarks' && detail?.landmarks && (
                            <section className="animate-fade-in">
                                <h2 className="flex items-center gap-3 text-3xl font-cinematic font-bold text-white mb-8 pb-2 border-b border-white/10">
                                    <FaMonument className="text-saffron" /> Key Landmarks
                                </h2>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {detail.landmarks.map((l, i) => (
                                        <AttractionCard key={i} title={l.title} desc={l.desc} mustSee={l.mustSee} />
                                    ))}
                                </div>
                            </section>
                        )}

                        {/* FOOD TAB */}
                        {activeTab === 'food' && detail && (
                            <section className="animate-fade-in">
                                <h2 className="flex items-center gap-3 text-3xl font-cinematic font-bold text-white mb-8 pb-2 border-b border-white/10">
                                    <FaUtensils className="text-saffron" /> Food & Culture
                                </h2>
                                <div className="space-y-8">
                                    {detail.food && (
                                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                            {detail.food.map((f, i) => (
                                                <FoodCard key={i} name={f.name} type={f.type} price={f.price} desc={f.desc} />
                                            ))}
                                        </div>
                                    )}
                                    {detail.budget && (
                                        <div className="bg-white/5 border border-white/10 rounded-xl p-6">
                                            <h3 className="text-xl font-cinematic font-bold text-white mb-4">💰 Budget Estimate (Per Person)</h3>
                                            <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                                                {detail.budget.map((b, i) => (
                                                    <BudgetItem key={i} label={b.label} value={b.value} highlight={b.highlight} />
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </section>
                        )}

                        {/* TREK GUIDE TAB */}
                        {activeTab === 'trek' && detail && (
                            <section className="animate-fade-in">
                                <h2 className="flex items-center gap-3 text-3xl font-cinematic font-bold text-white mb-8 pb-2 border-b border-white/10">
                                    <FaHiking className="text-saffron" /> Trek & Travel Guide
                                </h2>
                                <div className="space-y-8">
                                    {/* Trek Routes */}
                                    {detail.trekRoutes && (
                                        <div>
                                            <h3 className="text-xl font-cinematic font-bold text-saffron mb-4">Trek Routes</h3>
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                {detail.trekRoutes.map((r, i) => (
                                                    <TrekCard key={i} {...r} />
                                                ))}
                                            </div>
                                        </div>
                                    )}

                                    {/* How to Reach */}
                                    {detail.howToReach && (
                                        <div className="relative border-l-2 border-saffron/30 pl-6">
                                            <h3 className="text-xl font-cinematic font-bold text-saffron mb-4">How to Reach</h3>
                                            <div className="space-y-6">
                                                {detail.howToReach.map((h, i) => (
                                                    <div key={i} className="flex gap-4">
                                                        <div className="w-12 h-12 rounded-full bg-white/10 flex items-center justify-center flex-shrink-0">
                                                            <span className="text-saffron text-xl">{h.icon}</span>
                                                        </div>
                                                        <div>
                                                            <h4 className="font-bold text-white">{h.mode}</h4>
                                                            <p className="text-gray-400 text-sm mt-1">{h.desc}</p>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    )}

                                    {/* Trek Essentials */}
                                    {detail.trekEssentials && (
                                        <div className="bg-white/5 border border-white/10 rounded-xl p-6">
                                            <h3 className="text-xl font-cinematic font-bold text-saffron mb-4">🎒 Trek Essentials</h3>
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-300">
                                                {detail.trekEssentials.map((tip, i) => (
                                                    <div key={i} className="flex items-center gap-2">
                                                        <span className="text-saffron">✓</span> {tip}
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </section>
                        )}

                        {/* SAFETY ALERTS — always visible when detail exists */}
                        {detail?.safetyAlerts && (
                            <section className="bg-red-500/5 border border-red-500/20 rounded-2xl p-6">
                                <h3 className="flex items-center gap-3 text-xl font-cinematic font-bold text-red-400 mb-4">
                                    <FaExclamationTriangle /> Safety Alerts
                                </h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    {detail.safetyAlerts.map((alert, i) => (
                                        <div key={i} className="flex items-start gap-3">
                                            <span className="text-red-400 mt-1">⚠</span>
                                            <div>
                                                <p className="text-white font-medium">{alert.msg}</p>
                                                <p className="text-sm text-gray-400">Season: {alert.season}</p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                                <div className="mt-4 pt-4 border-t border-red-500/20 flex flex-wrap gap-6 text-sm">
                                    <span className="text-gray-300"><strong className="text-white">Police:</strong> 100</span>
                                    <span className="text-gray-300"><strong className="text-white">Ambulance:</strong> 108</span>
                                    <span className="text-gray-300"><strong className="text-white">Emergency:</strong> 112</span>
                                </div>
                            </section>
                        )}

                        {/* VISITOR REVIEWS */}
                        {detail?.reviews && (
                            <section>
                                <h2 className="flex items-center gap-3 text-3xl font-cinematic font-bold text-white mb-6">
                                    <FaStar className="text-saffron" /> What Visitors Say
                                </h2>
                                <div className="bg-white/5 border border-white/10 rounded-xl p-6">
                                    <p className="italic text-xl text-gray-200 text-center mb-6">
                                        "{detail.reviews.quote}"
                                    </p>
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                        <div>
                                            <h4 className="text-saffron font-bold text-sm uppercase tracking-wider mb-3">Top Positives</h4>
                                            <ul className="space-y-2">
                                                {detail.reviews.positives.map((item, i) => (
                                                    <li key={i} className="flex items-center gap-2 text-gray-300">
                                                        <span className="text-green-400">✓</span> {item}
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                        <div>
                                            <h4 className="text-saffron font-bold text-sm uppercase tracking-wider mb-3">Pro Tips</h4>
                                            <ul className="space-y-2">
                                                {detail.reviews.proTips.map((item, i) => (
                                                    <li key={i} className="flex items-center gap-2 text-gray-300">
                                                        <span className="text-saffron">💡</span> {item}
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    </div>
                                    <div className="mt-4 pt-4 border-t border-white/10 flex items-center justify-center gap-2">
                                        <span className="text-saffron text-lg">⭐</span>
                                        <span className="text-white font-bold">{detail.reviews.rating}</span>
                                        <span className="text-gray-400 text-sm">({detail.reviews.reviewCount} reviews)</span>
                                    </div>
                                </div>
                            </section>
                        )}

                        {/* Agent Data — enriched sections */}
                        {agentData?.highlights && agentData.highlights.length > 0 && (
                            <section className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 sm:p-8">
                                <h2 className="flex items-center gap-3 text-2xl font-cinematic font-bold mb-4">
                                    <FaStar className="text-amber-500" /> Agent Highlights
                                </h2>
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                    {agentData.highlights.map((h, i) => (
                                        <div key={i} className="flex items-start gap-2 p-3 bg-amber-500/5 border border-amber-500/10 rounded-xl">
                                            <span className="text-amber-500 mt-0.5">✦</span>
                                            <span className="text-gray-300 text-sm">{h}</span>
                                        </div>
                                    ))}
                                </div>
                            </section>
                        )}

                        {/* Fort Agent CTA — only if no detail AND no agent data */}
                        {!hasDetail && !agentData && (
                            <section className="relative overflow-hidden bg-gradient-to-br from-saffron/5 via-white/[0.02] to-blue-500/5 border border-saffron/20 rounded-2xl p-6 sm:p-8">
                                <div className="absolute top-0 right-0 w-40 h-40 bg-saffron/5 rounded-full blur-3xl"></div>
                                <div className="relative">
                                    <div className="flex items-center gap-3 mb-3">
                                        <div className="w-10 h-10 rounded-xl bg-saffron/20 flex items-center justify-center">
                                            <FaRobot className="text-saffron" />
                                        </div>
                                        <div>
                                            <h3 className="font-cinematic font-bold text-lg">Fort Data Agent</h3>
                                            <p className="text-gray-500 text-xs">AI-powered enrichment from Wikipedia, Maps &amp; more</p>
                                        </div>
                                    </div>
                                    <p className="text-gray-400 text-sm mb-4">
                                        Get enriched data about this fort — detailed history, coordinates, reviews, highlights — all collected in real-time.
                                    </p>
                                    {agentLoading ? (
                                        <div className="space-y-2">
                                            <div className="flex items-center gap-2 text-saffron text-sm font-bold">
                                                <div className="w-4 h-4 border-2 border-saffron border-t-transparent rounded-full animate-spin"></div>
                                                Agent collecting data...
                                            </div>
                                            <div className="bg-black/30 rounded-lg p-3 max-h-32 overflow-y-auto font-mono text-xs space-y-1">
                                                {agentLogs.map((log, i) => (
                                                    <div key={i} className="text-green-400/80">→ {log}</div>
                                                ))}
                                            </div>
                                        </div>
                                    ) : (
                                        <button onClick={runAgent}
                                            className="inline-flex items-center gap-2 px-5 py-2.5 bg-saffron/10 border border-saffron/30 rounded-xl text-saffron font-bold text-sm hover:bg-saffron/20 transition-all">
                                            <FaRobot /> Run Fort Agent (~15s)
                                        </button>
                                    )}
                                </div>
                            </section>
                        )}
                    </div>

                    {/* ═══ RIGHT COLUMN: STICKY SIDEBAR ═══ */}
                    <div className="lg:w-1/3">
                        <div className="sticky top-28 space-y-6">

                            {/* Visiting Info Card */}
                            <div className="bg-royal-gray/60 backdrop-blur-xl border border-white/10 shadow-[0_0_30px_rgba(255,153,51,0.15)] rounded-2xl p-8 relative overflow-hidden">
                                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-saffron to-transparent opacity-70"></div>
                                <h3 className="text-2xl font-cinematic font-bold text-white mb-6 flex items-center gap-2">
                                    <FaMapMarkerAlt className="text-saffron" /> Visiting Information
                                </h3>
                                <ul className="space-y-6">
                                    <SideInfoItem icon={FaClock} label="Timings" value={fort.timings || 'Sunrise to Sunset'} />
                                    <SideInfoItem icon={FaRupeeSign} label="Entry Fee" value={fort.entryFee || 'Free'} />
                                    <SideInfoItem icon={FaCalendarAlt} label="Best Time" value={fort.bestTimeToVisit || 'October to February'} />
                                    <SideInfoItem icon={FaMountain} label="Altitude" value={fort.altitude || 'N/A'} />
                                </ul>
                                <div className="mt-6 flex flex-wrap gap-3">
                                    <button onClick={downloadTextItinerary}
                                        className="flex items-center gap-2 px-4 py-2.5 bg-saffron/10 border border-saffron/30 rounded-xl text-saffron font-bold text-sm hover:bg-saffron/20 transition-all">
                                        <FaDownload /> Itinerary (.txt)
                                    </button>
                                    <EmergencyButton fort={fort} />
                                </div>
                                <div className="mt-4">
                                    <CrowdStatusBadge fortId={fort._id} />
                                </div>
                                <button onClick={() => setShowMap(!showMap)}
                                    className="w-full mt-6 py-4 bg-saffron text-royal-black font-bold rounded-xl hover:bg-white transition-all duration-300 shadow-lg shadow-saffron/20">
                                    {showMap ? 'HIDE MAP' : 'GET DIRECTIONS'}
                                </button>
                            </div>

                            {/* Quick Facts */}
                            {detail?.quickFacts && (
                                <div className="bg-royal-gray/60 backdrop-blur-xl border border-white/10 rounded-2xl p-6 relative overflow-hidden">
                                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-orange-500 to-transparent opacity-50"></div>
                                    <h4 className="text-lg font-cinematic font-bold text-white mb-4 flex items-center gap-2">
                                        <FaMountain className="text-orange-400" /> Quick Facts
                                    </h4>
                                    <div className="space-y-3 text-sm">
                                        {detail.quickFacts.map((f, i) => (
                                            <FactItem key={i} label={f.label} value={f.value} />
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Facilities */}
                            {detail?.facilities && (
                                <div className="bg-royal-gray/60 backdrop-blur-xl border border-white/10 rounded-2xl p-6 relative overflow-hidden">
                                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-green-500 to-transparent opacity-50"></div>
                                    <h4 className="text-lg font-cinematic font-bold text-white mb-4">Facilities</h4>
                                    <div className="grid grid-cols-2 gap-3 text-sm">
                                        {detail.facilities.map((f, i) => (
                                            <FacilityBadge key={i} label={f.label} available={f.available} detail={f.detail} />
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Quick Info (fallback for non-detailed forts) */}
                            {!hasDetail && (
                                <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6">
                                    <h3 className="font-cinematic font-bold text-lg mb-4 flex items-center gap-2">
                                        <GiCastle className="text-saffron" /> Quick Info
                                    </h3>
                                    <div className="space-y-3">
                                        <InfoRow icon={<FaHiking className="text-saffron" />} label="Difficulty" value={fort.difficulty} />
                                        <InfoRow icon={<FaMountain className="text-blue-400" />} label="Altitude" value={fort.altitude || 'N/A'} />
                                        <InfoRow icon={<FaTicketAlt className="text-emerald-400" />} label="Entry Fee" value={fort.entryFee || 'Free'} />
                                        <InfoRow icon={<FaClock className="text-purple-400" />} label="Timings" value={fort.timings || 'Sunrise to Sunset'} />
                                        <InfoRow icon={<FaCalendarAlt className="text-amber-400" />} label="Best Time" value={fort.bestTimeToVisit || 'Oct - Feb'} />
                                    </div>
                                </div>
                            )}

                            {/* Action Buttons */}
                            <div className="space-y-3">
                                <a href={googleMapsUrl} target="_blank" rel="noopener noreferrer"
                                    className="flex items-center justify-between w-full px-5 py-3.5 bg-blue-500/10 border border-blue-500/20 rounded-xl text-blue-400 font-bold text-sm hover:bg-blue-500/20 transition-all">
                                    <span className="flex items-center gap-2"><FaMapMarkerAlt /> Open in Google Maps</span>
                                    <FaExternalLinkAlt size={12} />
                                </a>
                                {agentData?.wikipedia?.url && (
                                    <a href={agentData.wikipedia.url} target="_blank" rel="noopener noreferrer"
                                        className="flex items-center justify-between w-full px-5 py-3.5 bg-white/[0.03] border border-white/10 rounded-xl text-gray-300 font-bold text-sm hover:text-white hover:border-white/20 transition-all">
                                        <span className="flex items-center gap-2"><FaWikipediaW /> Wikipedia Article</span>
                                        <FaExternalLinkAlt size={12} />
                                    </a>
                                )}
                                <Link to="/fort-agent"
                                    className="flex items-center justify-between w-full px-5 py-3.5 bg-saffron/10 border border-saffron/20 rounded-xl text-saffron font-bold text-sm hover:bg-saffron/20 transition-all">
                                    <span className="flex items-center gap-2"><FaRobot /> Explore with Fort Agent</span>
                                    <FaChevronRight size={12} />
                                </Link>
                            </div>

                            {/* Nearby Forts */}
                            <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6">
                                <h3 className="font-cinematic font-bold text-lg mb-4">Nearby Forts</h3>
                                <div className="space-y-2">
                                    {staticForts
                                        .filter(f => f.location?.district === fort.location?.district && f._id !== fort._id)
                                        .slice(0, 5)
                                        .map(f => (
                                            <Link key={f._id}
                                                to={f.hasDetailPage ? `/${f._id === 'janjira' ? 'murud-janjira' : f._id}` : `/fort/${f._id}`}
                                                onClick={() => window.scrollTo(0, 0)}
                                                className="flex items-center justify-between p-3 bg-white/[0.02] border border-white/5 rounded-xl hover:border-saffron/20 hover:bg-white/[0.03] transition-all group">
                                                <div>
                                                    <p className="text-sm font-bold text-white group-hover:text-saffron transition-colors">{f.name.replace(' Fort', '')}</p>
                                                    <p className="text-xs text-gray-600">{f.difficulty} • {f.altitude || 'N/A'}</p>
                                                </div>
                                                <FaChevronRight className="text-gray-700 group-hover:text-saffron transition-colors" size={10} />
                                            </Link>
                                        ))}
                                    {staticForts.filter(f => f.location?.district === fort.location?.district && f._id !== fort._id).length === 0 && (
                                        <p className="text-gray-600 text-sm">No other forts in {fort.location?.district} district</p>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Google Maps Embed */}
                {showMap && (
                    <div className="mt-12 rounded-2xl overflow-hidden border border-white/10">
                        <iframe
                            title={`${fort.name} Map`}
                            width="100%"
                            height="400"
                            style={{ border: 0 }}
                            loading="lazy"
                            src={`https://maps.google.com/maps?q=${encodeURIComponent(fort.name + ' Maharashtra')}&output=embed`}
                        />
                    </div>
                )}
            </div>
        </div>
    );
};

/* ═══════════════════════════════════════════════
   MINI COMPONENTS
   ═══════════════════════════════════════════════ */

const QuickStat = ({ icon, label, value }) => (
    <div className="flex items-center gap-3 px-4 py-2">
        <span className="text-2xl">{icon}</span>
        <div>
            <p className="text-[10px] text-gray-500 uppercase tracking-widest">{label}</p>
            <p className="text-white font-bold text-sm">{value}</p>
        </div>
    </div>
);

const TimelineItem = ({ year, title, desc }) => (
    <div className="relative pl-8 pb-2">
        <div className="absolute left-0 top-1 w-4 h-4 rounded-full bg-saffron/20 border-2 border-saffron"></div>
        <div className="absolute left-[7px] top-5 w-0.5 h-full bg-saffron/10"></div>
        <span className="text-saffron font-bold text-sm uppercase tracking-wider">{year}</span>
        <h4 className="text-lg font-bold text-white mt-1">{title}</h4>
        <p className="text-gray-400 mt-1">{desc}</p>
    </div>
);

const AttractionCard = ({ title, desc, mustSee }) => (
    <div className="bg-white/5 border border-white/10 p-5 rounded-xl hover:bg-white/10 hover:border-saffron/50 transition-all duration-300 group relative">
        {mustSee && (
            <span className="absolute top-3 right-3 text-[10px] font-bold uppercase tracking-wider bg-saffron/20 text-saffron px-2 py-0.5 rounded-full border border-saffron/30">
                Must See
            </span>
        )}
        <h4 className="text-lg font-bold text-white mb-2 group-hover:text-saffron transition-colors">{title}</h4>
        <p className="text-sm text-gray-400">{desc}</p>
    </div>
);

const FoodCard = ({ name, type, price, desc }) => (
    <div className="bg-white/5 border border-white/10 p-5 rounded-xl hover:bg-white/10 transition-all duration-300">
        <div className="flex items-center justify-between mb-2">
            <h4 className="text-lg font-bold text-white">{name}</h4>
            <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-full ${type === 'Veg' ? 'bg-green-500/20 text-green-400 border border-green-500/30'
                : type === 'Beverage' ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                    : 'bg-red-500/20 text-red-400 border border-red-500/30'
                }`}>{type}</span>
        </div>
        <p className="text-sm text-gray-400 mb-2">{desc}</p>
        <p className="text-saffron font-bold text-sm">{price}</p>
    </div>
);

const TrekCard = ({ icon, title, difficulty, distance, time, desc }) => (
    <div className="bg-white/5 border border-white/10 p-5 rounded-xl hover:bg-white/10 hover:border-saffron/50 transition-all duration-300 group">
        <div className="flex items-center gap-2 mb-3">
            <span className="text-xl">{icon}</span>
            <h4 className="text-lg font-bold text-white group-hover:text-saffron transition-colors">{title}</h4>
        </div>
        <div className="flex gap-3 mb-3 text-xs">
            <span className="bg-saffron/10 text-saffron px-2 py-1 rounded">{difficulty}</span>
            <span className="bg-white/10 text-gray-300 px-2 py-1 rounded">{distance}</span>
            <span className="bg-white/10 text-gray-300 px-2 py-1 rounded">{time}</span>
        </div>
        <p className="text-sm text-gray-400">{desc}</p>
    </div>
);

const BudgetItem = ({ label, value, highlight }) => (
    <div className={`text-center p-3 rounded-lg ${highlight ? 'bg-saffron/20 border border-saffron/30' : 'bg-white/5'}`}>
        <p className="text-xs text-gray-400 uppercase tracking-wider">{label}</p>
        <p className={`font-bold mt-1 ${highlight ? 'text-saffron text-lg' : 'text-white'}`}>{value}</p>
    </div>
);

const SideInfoItem = ({ icon: Icon, label, value }) => (
    <li className="flex items-start gap-4">
        <div className="bg-saffron/10 p-3 rounded-lg text-saffron shrink-0"><Icon size={20} /></div>
        <div>
            <span className="block text-sm text-saffron font-bold uppercase tracking-wider mb-1">{label}</span>
            <span className="text-white font-medium leading-snug block">{value}</span>
        </div>
    </li>
);

const FactItem = ({ label, value }) => (
    <div className="flex justify-between items-center py-1 border-b border-white/5">
        <span className="text-gray-400">{label}</span>
        <span className="text-white font-medium text-right">{value}</span>
    </div>
);

const FacilityBadge = ({ label, available, detail }) => (
    <div className={`p-2 rounded-lg text-center ${available ? 'bg-green-500/10 border border-green-500/20' : 'bg-red-500/10 border border-red-500/20'}`}>
        <span className={`text-xs font-bold ${available ? 'text-green-400' : 'text-red-400'}`}>
            {available ? '✓' : '✗'} {label}
        </span>
        <p className="text-[10px] text-gray-400 mt-0.5">{detail}</p>
    </div>
);

const InfoRow = ({ icon, label, value }) => (
    <div className="flex items-center justify-between py-2 border-b border-white/5 last:border-0">
        <span className="flex items-center gap-2 text-gray-500 text-sm">{icon} {label}</span>
        <span className="text-white text-sm font-bold text-right max-w-[55%]">{value}</span>
    </div>
);

export default FortDetails;
